app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
    old-links-hour-period: 1

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

scrapper:
  github:
    baseUrl: https://api.github.com
  stackoverflow:
    baseUrl: https://api.stackexchange.com/2.3
    questionsPath: /questions
    questionAnswersPath: /answers
    questionCommentsPath: /comments

clients:
  bot:
    baseUrl: http://localhost:8090
    updatesPath: /updates

springdoc:
  swagger-ui:
    path: /swagger-ui

