app:
  telegram-token: ${TELEGRAM_API_KEY}
  allowed-domains: github.com,stackoverflow.com

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

clients:
  scrapper:
    baseUrl: http://localhost:8080
    tgChatPath: /tg-chat
    linksPath: /links
    chatIdHeader: Tg-Chat-Id
    backOffPolicy: constant

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
