/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.domain.jooq.tables.records;

import edu.java.scrapper.domain.jooq.tables.UsersLinks;
import java.beans.ConstructorProperties;
import org.jetbrains.annotations.NotNull;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UsersLinksRecord extends UpdatableRecordImpl<UsersLinksRecord> implements Record2<Integer, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>USERS_LINKS.LINK_ID</code>.
     */
    public void setLinkId(@NotNull Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>USERS_LINKS.LINK_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Integer getLinkId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>USERS_LINKS.USER_TG_ID</code>.
     */
    public void setUserTgId(@NotNull Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>USERS_LINKS.USER_TG_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getUserTgId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record2<Integer, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Integer, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row2<Integer, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Integer> field1() {
        return UsersLinks.USERS_LINKS.LINK_ID;
    }

    @Override
    @NotNull
    public Field<Long> field2() {
        return UsersLinks.USERS_LINKS.USER_TG_ID;
    }

    @Override
    @NotNull
    public Integer component1() {
        return getLinkId();
    }

    @Override
    @NotNull
    public Long component2() {
        return getUserTgId();
    }

    @Override
    @NotNull
    public Integer value1() {
        return getLinkId();
    }

    @Override
    @NotNull
    public Long value2() {
        return getUserTgId();
    }

    @Override
    @NotNull
    public UsersLinksRecord value1(@NotNull Integer value) {
        setLinkId(value);
        return this;
    }

    @Override
    @NotNull
    public UsersLinksRecord value2(@NotNull Long value) {
        setUserTgId(value);
        return this;
    }

    @Override
    @NotNull
    public UsersLinksRecord values(@NotNull Integer value1, @NotNull Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersLinksRecord
     */
    public UsersLinksRecord() {
        super(UsersLinks.USERS_LINKS);
    }

    /**
     * Create a detached, initialised UsersLinksRecord
     */
    @ConstructorProperties({ "linkId", "userTgId" })
    public UsersLinksRecord(@NotNull Integer linkId, @NotNull Long userTgId) {
        super(UsersLinks.USERS_LINKS);

        setLinkId(linkId);
        setUserTgId(userTgId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised UsersLinksRecord
     */
    public UsersLinksRecord(edu.java.scrapper.domain.jooq.tables.pojos.UsersLinks value) {
        super(UsersLinks.USERS_LINKS);

        if (value != null) {
            setLinkId(value.getLinkId());
            setUserTgId(value.getUserTgId());
            resetChangedOnNotNull();
        }
    }
}
