/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.domain.jooq;

import edu.java.scrapper.domain.jooq.tables.Links;
import edu.java.scrapper.domain.jooq.tables.Users;
import edu.java.scrapper.domain.jooq.tables.UsersLinks;
import edu.java.scrapper.domain.jooq.tables.records.LinksRecord;
import edu.java.scrapper.domain.jooq.tables.records.UsersLinksRecord;
import edu.java.scrapper.domain.jooq.tables.records.UsersRecord;
import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<LinksRecord> CONSTRAINT_4 = Internal.createUniqueKey(Links.LINKS, DSL.name("CONSTRAINT_4"), new TableField[] { Links.LINKS.ID }, true);
    public static final UniqueKey<LinksRecord> CONSTRAINT_45 = Internal.createUniqueKey(Links.LINKS, DSL.name("CONSTRAINT_45"), new TableField[] { Links.LINKS.URL }, true);
    public static final UniqueKey<UsersRecord> CONSTRAINT_4D = Internal.createUniqueKey(Users.USERS, DSL.name("CONSTRAINT_4D"), new TableField[] { Users.USERS.TG_ID }, true);
    public static final UniqueKey<UsersLinksRecord> CONSTRAINT_AD6 = Internal.createUniqueKey(UsersLinks.USERS_LINKS, DSL.name("CONSTRAINT_AD6"), new TableField[] { UsersLinks.USERS_LINKS.LINK_ID, UsersLinks.USERS_LINKS.USER_TG_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<UsersLinksRecord, LinksRecord> CONSTRAINT_A = Internal.createForeignKey(UsersLinks.USERS_LINKS, DSL.name("CONSTRAINT_A"), new TableField[] { UsersLinks.USERS_LINKS.LINK_ID }, Keys.CONSTRAINT_4, new TableField[] { Links.LINKS.ID }, true);
    public static final ForeignKey<UsersLinksRecord, UsersRecord> CONSTRAINT_AD = Internal.createForeignKey(UsersLinks.USERS_LINKS, DSL.name("CONSTRAINT_AD"), new TableField[] { UsersLinks.USERS_LINKS.USER_TG_ID }, Keys.CONSTRAINT_4D, new TableField[] { Users.USERS.TG_ID }, true);
}
