name: Scrapper Build

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/scrapper.yml
      - link-parser/**
      - scrapper/**

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: maven build
        run: mvn -pl scrapper -am package

      - name: set lower case image name
        run: echo "IMAGE_NAME_LOWERCASE=${IMAGE_NAME,,}" >>${GITHUB_ENV}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image and push to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: scrapper/Dockerfile
          build-args: JAR_FILE=scrapper/target/scrapper*.jar
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWERCASE }}/scrapper:latest

      - id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        if: ( github.event_name != 'workflow_dispatch' )
        with:
          paths: ${{ github.workspace }}/scrapper/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 30
          min-coverage-changed-files: 30
          title: Code Coverage
          update-comment: true

  checkstyle:
    name: checkstyle
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - run: mvn -pl scrapper -am checkstyle:check

  integration-test:
    name: integration tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - run: mvn -pl scrapper -am verify -Dskip.unit.tests=true
